# Generated by Django 4.2.4 on 2023-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_toss_payment_data_order_toss_payment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toss_order_id',
            field=models.CharField(max_length=50, null=True, unique=True), # Default 값을 지워줘야 함
        ),
    ]
